server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: wjdehddnr1@

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

movie:
  peopleList-api:
    url: http://www.kobis.or.kr/kobisopenapi/webservice/rest/people/searchPeopleList.json
    key: 02b247af5f8446cb1a02deaebc9917bf
    curPage: 1
    itemPerPage: 100
    peopleName:
    filmographyName:
    chunk: 1
    skipLimit: 1679
    cron: 0 23 16 * * ?
  people-api:
    url: http://www.kobis.or.kr/kobisopenapi/webservice/rest/people/searchPeopleInfo.json
    key: 02b247af5f8446cb1a02deaebc9917bf
    peopleCode:
    chunk: 10
    csv-path: C:\\Users\\nb18-03hp\\csv\\peopleList.csv